name: Deploy Doxygen to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update && sudo apt-get install -y graphviz
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_14_0/doxygen-1.14.0.linux.bin.tar.gz
          tar -xzf doxygen-1.14.0.linux.bin.tar.gz
          sudo mv doxygen-1.14.0/bin/doxygen /usr/local/bin/doxygen
          doxygen -v
          
      - name: Fetch Tagfiles
        run: |
          wget https://nsmbu.github.io/Sys/Sys.tag -O Sys.tag
          wget https://nsmbu.github.io/Eft/Eft.tag -O Eft.tag
          wget https://nsmbu.github.io/FFL/FFL.tag -O FFL.tag
          wget https://nsmbu.github.io/G3d/G3d.tag -O G3d.tag
          wget https://nsmbu.github.io/Lyt/Lyt.tag -O Lyt.tag
          wget https://nsmbu.github.io/Snd/Snd.tag -O Snd.tag

      - name: Generate Documentation
        run: doxygen

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
